import {
  REQUIRED_DOCUMENTS_FOR_LISTING,
  AUTO_GENERATED_DOCUMENTS_ON_INVESTMENT,
  OwnerDocRequirement,
} from "@/lib/projects";
import { Card } from "@/components/ui/card";
import { CheckCircle, FileText, Clock } from "lucide-react";

export interface ProjectDocumentRequirementsProps {
  showRequired?: boolean;
  showAutoGenerated?: boolean;
}

export function ProjectDocumentRequirements({
  showRequired = true,
  showAutoGenerated = true,
}: ProjectDocumentRequirementsProps) {
  return (
    <div className="space-y-6">
      {/* Required Documents for Listing */}
      {showRequired && (
        <Card className="border border-border p-6">
          <div className="mb-4 flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            <h3 className="font-display text-lg font-bold">الوثائق المطلوبة قبل طرح المشروع</h3>
          </div>
          
          <p className="mb-4 text-sm text-muted-foreground">
            يجب توفير هذه الوثائق المطلوبة قبل إدراج المشروع على المنصة:
          </p>

          <div className="grid gap-3">
            {REQUIRED_DOCUMENTS_FOR_LISTING.map((doc) => (
              <DocumentRequirementRow key={doc.key} doc={doc} type="required" />
            ))}
          </div>

          <div className="mt-4 rounded-lg border-l-4 border-amber-500 bg-amber-50 p-3 text-sm text-amber-900">
            <p className="font-semibold">ملاحظة مهمة:</p>
            <p className="mt-1">تأكد من توفير جميع الوثائق المطلوبة قبل تقديم المشروع للمراجعة.</p>
          </div>
        </Card>
      )}

      {/* Auto-Generated Documents on Investment */}
      {showAutoGenerated && (
        <Card className="border border-border p-6">
          <div className="mb-4 flex items-center gap-2">
            <Clock className="h-5 w-5 text-emerald-600" />
            <h3 className="font-display text-lg font-bold">الوثائق المُنتجة تلقائياً عند الاستثمار</h3>
          </div>

          <p className="mb-4 text-sm text-muted-foreground">
            سيتم إنشاء هذه الوثائق تلقائياً عند استثمار المستثمرين في المشروع:
          </p>

          <div className="grid gap-3">
            {AUTO_GENERATED_DOCUMENTS_ON_INVESTMENT.map((doc) => (
              <DocumentRequirementRow key={doc.key} doc={doc} type="auto-generated" />
            ))}
          </div>

          <div className="mt-4 rounded-lg border-l-4 border-emerald-500 bg-emerald-50 p-3 text-sm text-emerald-900">
            <p className="font-semibold">معلومة:</p>
            <p className="mt-1">
              يتم إنشاء هذه الوثائق تلقائياً وتسليمها للمستثمرين بشكل فوري عند اكتمال عملية الاستثمار.
            </p>
          </div>
        </Card>
      )}
    </div>
  );
}

interface DocumentRequirementRowProps {
  doc: OwnerDocRequirement;
  type: "required" | "auto-generated";
}

function DocumentRequirementRow({ doc, type }: DocumentRequirementRowProps) {
  const icon = type === "required" ? (
    <FileText className="h-4 w-4 text-amber-600" />
  ) : (
    <CheckCircle className="h-4 w-4 text-emerald-600" />
  );

  return (
    <div className="flex items-center justify-between rounded-lg border border-border/50 bg-background/50 p-3">
      <div className="flex items-center gap-3">
        {icon}
        <div className="flex-1">
          <p className="font-medium text-foreground">{doc.label}</p>
          <p className="text-xs text-muted-foreground">{doc.key}</p>
        </div>
      </div>
      {doc.required && (
        <div className="rounded-full bg-red-100 px-3 py-1 text-xs font-semibold text-red-700">
          إجباري
        </div>
      )}
    </div>
  );
}
